- name: Run Terraform on localhost
  hosts: localhost  
  gather_facts: no  

  tasks:
    - name: Run terraform init
      command: terraform init
      args:
        chdir: ../terraform  

    - name: Run terraform apply
      command: terraform apply -auto-approve
      args:
        chdir: ../terraform  
